tid_portal/accounts/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import change_password


urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('password_change/', change_password, name='password_change'),
]

tid_portal/band_portal/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token    # Getting_token

from . import views

app_name = 'band_portal'
urlpatterns = [
    path('', views.index, name='index'),
    path('projects/', views.projects, name='projects'),
    path('projects/<str:project_slug>/', views.project, name='project'),
    path('projects/<str:project_slug>/add-tabulature', views.project_add_tabulature, name='project_add_tabulature'),
    path('projects/<str:project_slug>/add-lyrics', views.project_add_lyrics, name='project_add_lyrics'),
    path('projects/<str:project_slug>/add-misc-file', views.project_add_resource_file, name='project_add_resource_file'),
    path('projects/<str:project_slug>/add-url', views.project_add_related_url, name='project_add_related_url'),
    path('projects/<str:project_slug>/add-event', views.project_add_event, name='project_add_event'),
    path('projects/<str:project_slug>/edit-statuses', views.project_edit_statuses, name='project_edit_statuses'),
    path('projects/<str:project_slug>/edit-name', views.project_edit_name, name='project_edit_name'),
    path('projects/<str:project_slug>/completed-tasks', views.project_completed_tasks, name='project_completed_tasks'),
    path('projects/<str:project_slug>/add-task', views.project_add_task, name='project_add_task'),
    path('projects/<str:project_slug>/toggle_finished_task', views.project_toggle_finished_task, name='project_toggle_finished_task'),

    path('under-construction', views.under_construction, name='under_construction'),

    path('tasks/user-tasks/', views.user_tasks, name='user_tasks'),
    path('tasks/toggle-status/', views.tasks_toggle_status, name='tasks_toggle_status'),

    # Songs
    path('songs/', views.songs, name='songs'),
    path('songs/<str:song_artist>-<str:song_name>/', views.song, name='song'),
    path('songs/<str:song_artist>-<str:song_name>/edit', views.song_edit, name='song_edit'),
    path('songs/update/', views.song_update, name='song_update'),
    path('songs/live_list/', views.songs_live_list, name='songs_live_list'),
    path('songs/live_list/update', views.songs_live_list_update, name='songs_live_list_update'),
    path('songs/live_list_lookup/', views.songs_live_list_lookup, name='songs_live_list_lookup'),


    # Tabulatures
    path('tabulature/create', views.tabulature_create, name='tabulature_create'),
    path('tabulatures/', views.tabulatures, name='tabulatures'),
    path('tabulatures/<int:id>', views.tabulature, name='tabulature'),
    path('tabulatures/file-actuality/<int:id>', views.tabulature_file_actuality, name='tabulature_file_actuality'),
    path('tabulatures/file-delete/<int:id>', views.tabulature_file_delete, name='tabulature_file_delete'),
    path('tabulatures/file-add/<int:tabulature_id>', views.tabulature_file_add, name='tabulature_file_add'),
    path('tabulatures/', views.tabulatures, name='tabulatures'),
    path('tabulatures/download-actual', views.tabulatures_download_actual, name='tabulatures_download_actual'),
    path('tabulatures/download-notactual', views.tabulatures_download_notactual, name='tabulatures_download_notactual'),


    # Lyrics
    path('lyrics_list/', views.lyrics_list, name='lyrics_list'),
    path('lyrics/<int:id>', views.lyrics, name='lyrics'),


    #   Functional urls
    path('projects/create', views.project_create, name='project_create'),
    path('songs/create', views.song_create, name='song_create'),

    # REST
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),  # Getting_token
    path('rest/live-list/all', views.rest_get_live_list),
]

tid_portal/band_portal/models.py
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.core.validators import FileExtensionValidator
from django.dispatch import receiver
from django.db.models.signals import post_delete
from django.contrib.auth.models import User

from _datetime import datetime
from loguru import logger

from .logic import *
from tid_portal import settings

__all__ = ['Lyrics', 'Tabulature', 'TabulatureFile', 'Song', 'Project',
           'ProjectEvent', 'ProjectResourceFile', 'ProjectRelatedURL',
           'StatusValue', 'StatusCategory', 'ProjectStatusCategory',
           'ProjectTask']

logger.add(settings.BASE_DIR + "/debug.log", format="{time} {level} {message}", rotation="2 week", compression="zip")


class Lyrics(models.Model):
    """
    Lyrics file for song or project
    """


    pub_date = models.DateTimeField(default=datetime.now())
    file = models.FileField(upload_to='lyrics',
                            validators=[FileExtensionValidator(allowed_extensions=['txt', 'doc'])],
                            )

    def show_lyrics(self) -> str:
        """ Show text from lyrics file """

        logger.info("Trying to read file: {}".format(self.file.path))
        f = open(self.file.path, encoding="utf-8")
        file_content = f.read()
        f.close()
        return file_content

    def __str__(self):
        return "{0} {1}".format(self.file.name.split('/')[-1], self.pub_date)
    def filename(self):
        return self.file.name.split('/')[-1]

class Tabulature(models.Model):
    """
    Tab that will have different versions
    artist, name, project or song
    """


    name = models.CharField(max_length=30, verbose_name="Tabulature set name")

    def create_tabulature_file(self, file, is_actual: bool = False):
        """ Create TabulatureFile by file """

        tabulature_file = TabulatureFile()
        tabulature_file.tabulature = self
        tabulature_file.file.save(file.name, file)
        tabulature_file.is_actual = is_actual
        tabulature_file.save()

    def __str__(self):
        return self.name


class TabulatureFileQuerySet(models.QuerySet):
    """ Additional queries for ProjectEvent """


    def owned_by_project(self, tabulature):
        return self.filter(tabulature = tabulature).order_by('-is_actual', 'pub_date')


class TabulatureFile(models.Model):
    """
    Versions of a tab
    tabulature, pub_date, is_actual, file
    """


    tabulature = models.ForeignKey(
        Tabulature,
        on_delete=models.CASCADE,
        verbose_name="Tabulature",
        related_name='tab_files'
    )
    pub_date = models.DateTimeField(default=datetime.now(), verbose_name="Publication date")
    is_actual = models.BooleanField(default=False, verbose_name="Is actual file")
    file = models.FileField(upload_to='tabs', null=True,
                            validators=[FileExtensionValidator(allowed_extensions=['gpx', 'gp5', 'gp'])],
                            verbose_name="Tabulature file name"
                            )
    objects = TabulatureFileQuerySet.as_manager()

    def __str__(self):
        return "{0} {1}".format(self.tabulature.name, self.pub_date)

    def filename(self):
        return self.file.name.split('/')[-1]


class SongQuerySet(models.QuerySet):
    """ Additional queries for Songs - played, unplayed and live list """


    def live_list(self):
        return self.filter(live_position__gt=0).order_by('live_position')

    def played_only_on_practice(self):
        return self.filter(live_position=0).filter(played_now=True)

    def played_on_practice(self):
        return self.exclude(played_now=False).order_by('artist', 'name')

    def not_played(self):
        return self.exclude(played_now=True)


class Song(models.Model):
    """
    Song that we have played or plaing now on practice and lives.
    artist, name, tab, played_now
    """


    artist = models.CharField(max_length=100, verbose_name="Artist name")
    name = models.CharField(max_length = 100, verbose_name="Song name")
    played_now = models.BooleanField(default = False, verbose_name="Is played on practices")
    tempo = models.IntegerField(default=100, verbose_name="Tempo")
    live_position = models.IntegerField(default = 0, verbose_name="Position in live list")
    tabulature = models.ForeignKey(Tabulature,
                                   on_delete=models.SET_NULL,
                                   null=True,
                                   blank=True,
                                   verbose_name="Tabulature")
    lyrics = models.ForeignKey(Lyrics,
                               on_delete=models.SET_NULL,
                               null=True,
                               blank=True,
                               verbose_name="Lyrics")
    objects = SongQuerySet.as_manager()

    def __str__(self):
        return "{0} - {1}".format(self.artist, self.name)

    def save(self, *args, **kwargs):
        if settings.DEBUG:
            logger.info("Song was saved: {} {} {}".format(self.artist, self.name, self.tempo))
        super().save(*args, **kwargs)


class Project(models.Model):
    """
    Song that we recording, contains history, status and files
    name, created_date, is_released,
    """


    name = models.CharField(max_length=100, default="",
                            verbose_name="Project name")
    created_date = models.DateTimeField(default=datetime.now(),
                                        verbose_name="Created date")
    is_released = models.BooleanField(default=False,
                                      verbose_name="Project song is released")
    riffs_status = models.CharField(max_length=20,
                                    choices=StatusChoices.choices,
                                    default=StatusChoices.NOTDONE,
                                    verbose_name="Riffs readiness status")
    solo_status = models.CharField(max_length=20,
                                   choices=StatusChoices.choices,
                                   default=StatusChoices.NOTDONE,
                                   verbose_name="Solo readiness status")
    bass_status = models.CharField(max_length=20,
                                   choices=StatusChoices.choices,
                                   default=StatusChoices.NOTDONE,
                                   verbose_name="Bass readiness status")
    drums_status = models.CharField(max_length=20,
                                    choices=StatusChoices.choices,
                                    default=StatusChoices.NOTDONE,
                                    verbose_name="Drums readiness status")
    lyrics_status = models.CharField(max_length=20,
                                     choices=StatusChoices.choices,
                                     default=StatusChoices.NOTDONE,
                                     verbose_name="Lyrics readiness status")
    vox_status = models.CharField(max_length=20,
                                  choices=StatusChoices.choices,
                                  default=StatusChoices.NOTDONE,
                                  verbose_name="Vox readiness status")
    slug = models.SlugField(max_length=100, unique=True, null=True)
    tabulature = models.ForeignKey(Tabulature, on_delete=models.SET_NULL, null=True, blank=True)
    lyrics = models.ForeignKey(Lyrics, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name


class ProjectEventQuerySet(models.QuerySet):
    """ Additional queries for ProjectEvent """


    def owned_by_project(self, project_id: int):
        return self.filter(project__id=project_id).order_by('-pub_date')

    def last_events(self):
        return self.order_by('-pub_date')[0:10]


class ProjectEvent(models.Model):
    """
    Project history event - changed status, added new file or etc
    project, pub_date, note, author, is_important, is_deleted
    """


    project = models.ForeignKey(Project,
                                on_delete=models.CASCADE,
                                related_name='events', verbose_name="Related project")
    pub_date = models.DateTimeField(default=datetime.now(),
                                    verbose_name="Publication date")
    note = models.TextField(verbose_name="Note text")
    author = models.ForeignKey(User, null=True, blank=True,
                               on_delete=models.CASCADE,
                               verbose_name="Author")
    url = models.URLField(null=True,
                          blank=True,
                          verbose_name="Related URL")
    is_important = models.BooleanField(default=False,
                                       verbose_name="Event contains important info")
    is_deleted = models.BooleanField(default=False,
                                     verbose_name="Event marked for deletion")
    objects = ProjectEventQuerySet.as_manager()

    def __str__(self):
        return "{0} - {1} --- {2}".format(self.project.name, self.pub_date, self.note[:20])


class ProjectResourceFileQuerySet(models.QuerySet):
    """ Additional queries for ProjectEvent """


    def owned_by_project(self, project_id: int):
        return self.filter(project__id=project_id).order_by('-created_date')


class ProjectResourceFile(models.Model):
    """
    File related to project
    """


    project = models.ForeignKey(Project,
                                on_delete=models.CASCADE,
                                verbose_name="Related project")
    created_date = models.DateTimeField(default=datetime.now(), verbose_name="Creation date")
    description = models.CharField(max_length=200, verbose_name="Resource file description")
    file = models.FileField(upload_to='project_resource_files',
                            verbose_name="Resource file")

tid_portal/band_portal/forms.py
from django import  forms
from django.utils.translation import gettext_lazy as _


class TabulatureForm(forms.Form):
    tab_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label=_('Tabulature name'))
    tab_file = forms.FileField(widget=forms.FileInput(attrs={'class': 'form-control-file', 'accept':'.gpx,.gp,.gp5'}), label=_('Tabulature file'))

tid_portal/band_portal/templates/band_portal/base_backup.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="ru">
<head>
  {% get_current_language as LANGUAGE_CODE %}
<!-- Current language: {{ LANGUAGE_CODE }} -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v4.1.1">
  <title>Take It Down World Wide: {% block Title %}  Unnamed page {% endblock %}</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'band_portal/bootstrap.min.css' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'band_portal/tid_style.css' %}">
  </head>
<body>
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap pb-2 p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="{% url 'band_portal:index' %}">Take it Down \m/</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- Search line
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
   -->
  <div class="dropdown dropleft">
    <button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown">
      {{ user.first_name }}
    </button>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="{% url 'logout' %}">{% trans 'Sign out' %}</a>
      <a class="dropdown-item" href="{% url 'password_change' %}">{% trans 'Password change' %}</a>
    </div>
  </div>
  <!--
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="{% url 'logout' %}">{% trans 'Sign out' %}</a>
          <a class="nav-link" href="{% url 'password_change' %}">{% trans 'Password change' %}</a>
    </li>
  </ul>
  -->
</nav>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'band_portal:index' %}">
              <span data-feather="dashboard"></span>
              {% trans 'Dashboard' %}
            </a>
          </li>
          <!--
          <li class="nav-item">
            <h6>
              <span data-feather="manage_songs"></span>
              Manage songs
            </h6>
          </li>-->          <li class="nav-item">
            <a class="nav-link active" href="{% url 'band_portal:songs' %}">
              <span data-feather="songs"></span>
              {% trans 'Songs' %}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'band_portal:songs_live_list' %}">
              <span data-feather="live_list"></span>
              {% trans 'Manage Live list' %}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'band_portal:songs_live_list_lookup' %}">
              <span data-feather="live_list_lookup"></span>
              {% trans 'Live List Lookup' %}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'band_portal:tabulatures' %}">
              <span data-feather="tabulatures"></span>
              {% trans 'Tabulatures' %}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'band_portal:projects' %}">
              <span data-feather="projects"></span>
              {% trans 'Projects' %}
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">{% block SectionTitle %}Section Title {% endblock %}</h1>
          {% block AdditionalButtons %}
          {% endblock %}
        </div>

        <div>
            {% block Content %}
            Empty content
            {% endblock %}
        </div>
    </main>
  </div>
</div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
    <script src="{% static 'band_portal/js/jquery-sortable.js' %}"></script>
    <script src="{% static 'band_portal/js/bootstrap.js' %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    <script src="dashboard.js"></script>
  {% block AdditionalScripts %}
  {% endblock %}
  </body>
</html>

tid_portal/band_portal/templates/band_portal/project.html
{% extends 'band_portal/base.html' %}
{% load i18n %}

{% block Title %}
{{ project.name }}
{% endblock %}

{% block SectionTitle %}
<a class="text-secondary text-decoration-none" href="{% url 'band_portal:projects' %}">{% trans 'Projects| '%}</a>
{{ project.name }}
{% endblock %}

{% block AdditionalButtons %}
<div class="btn-toolbar mb-2 mb-md-0">
    <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:project_edit_name' project.slug %}">{% trans 'Rename' %}</a>
</div>
{% endblock %}

{% block Content %}
{% comment %}
{% if project.is_released %}
<span class="text-success">Released</span>
{% else %}
Not released
{% endif %}
<br />
{% endcomment %}

<p>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h3> {% trans 'Statuses' %} </h3>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:project_edit_statuses' project.slug %}">{% trans 'Change status' %}</a>
    </div>
</div>

<div>
    <table>
    {% for status_category in project.statuses.all %}
        <tr>
            <td>
                {{ status_category.category }}
            </td>
            <td>
                <span class="{{ status_category.status.styling_class }}"> {{ status_category.status.value }} </span>
            </td>
        </tr>
    {% endfor %}
    </table>
</div>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h3> {% trans 'Tasks' %} </h3>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:project_completed_tasks' project.slug %}">{% trans 'Completed' %}</a>
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:project_add_task' project.slug %}">{% trans 'Add task' %}</a>
    </div>
</div>
<div>
    <form id="statusForm" method="post" action="{% url 'band_portal:tasks_toggle_status' %}">
    {% csrf_token %}
    <input type="hidden" id="statusInput" name="task_id">
    </form>

    {% for task in tasks %}
    <div>
        <p>
            {{ task.description }}
        </p>
        {% for person in task.responsible_persons.all %}
            <span class="text-secondary"> {{ person.first_name }} {{ person.last_name }}| </span>
        {% endfor %}
        <br />
        <span class="text-secondary">{{ task.created_date }} </span>
        <br />
        {% if user in task.responsible_persons.all %}
        <button id="finish{{ task.id }}" class="btn btn-info mr-2" onclick="toggleStatus({{ task.id }})">{% trans 'Complete' %}</button>
        {% endif %}
        <hr />
    </div>

    {% endfor %}
</div>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h3> {% trans 'Related objects' %} </h3>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:project_add_resource_file' project.slug %}">{% trans 'Add file' %}</a>
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:project_add_related_url' project.slug %}">{% trans 'Add URL' %}</a>
        {% if not project.tabulature %}
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:project_add_tabulature' project.slug %}">{% trans 'Add tabulature' %}</a>
        {% else %}
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:project_add_tabulature' project.slug %}">{% trans 'Manage tabulature' %}</a>
        {% endif %}
        {% if not project.lyrics %}
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:project_add_lyrics' project.slug %}">{% trans 'Add Lyrics' %}</a>
        {% else %}
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:project_add_lyrics' project.slug %}">{% trans 'Manage Lyrics' %}</a>
        {% endif %}
    </div>
</div>
<div>
    {% if project.tabulature %}
        {% if project.tabulature.tabulaturefile_set %}
            <H6>{% trans 'Actual tabulatures' %}</H6>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <a class="text-secondary ml-2" href="{% url 'band_portal:tabulature' project.tabulature.id %}"> {% trans 'manage' %} </a>
                    {% comment %}
                    <!-- TODO: Нужно ли это? -->
                    <a class="text-secondary ml-2" href="{% url 'band_portal:under_construction' %}"> {% trans 'untie' %} </a>
                    {% endcomment %}
                </div>
            <ul>
            {% for tab in project.tabulature.tabulaturefile_set.all %}
                {% if tab.is_actual %}
                <li>
                    <a href="{{ tab.file.url }}">{{ tab.filename }}</a>
                </li>
                {% endif %}
            {% endfor %}
            </ul>
        {% endif %}
    {% endif %}
    {% if project.lyrics %}
    <a class="text-secondary" href="#lyrics{{ project.id }}" data-toggle="collapse">{% trans 'Lyrics' %}</a>
    <div id="lyrics{{ project.id }}" class="collapse">
    {{ project.lyrics.show_lyrics|linebreaks }}
    </div>
    {% endif %}
    {% if related_urls %}
    <div>
        <h6>{% trans 'Related URLs'%}</h6>
        <ul>
        {% for url in related_urls %}
            <li>
                <a class="text-secondary" href="{{ url.url }}" target="_blank">{{ url.description }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% if resource_files %}
    <div>
        <h6>{% trans 'Related files'%}</h6>
        <ul>
        {% for file in resource_files %}
            <li>
                <a class="text-secondary" href="{{ file.file.url }}" target="_blank">{{ file.description }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h3> {% trans 'Events and Notes' %} </h3>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:project_add_event' project.slug %}">{% trans 'New note' %}</a>
    </div>
</div>
{% for event in events%}
<div>
    <p>
        {{ event.note|linebreaksbr }}
        <br />
        <span class="text-secondary small">
            {% if event.author %}
            {{ event.author.last_name }} {{ event.author.first_name }} -
            {% endif %}
            {{ event.pub_date }}</span>
    </p>
</div>
{% endfor %}

{% endblock %}

{% block AdditionalScripts %}
<script>
const statusForm = document.getElementById('statusForm');
const formInput = statusForm.querySelector('#statusInput');

function toggleStatus(task_id)
{
    formInput.value = task_id;
    console.log(11111)

    statusForm.submit();
}
</script>
{% endblock %}

tid_portal/band_portal/templates/band_portal/project_add_base.html
{% extends 'band_portal/base.html' %}
{% load i18n %}

{% block Title %}
{{ project.name }}
{% block TitleAddition %}
{% endblock %}
{% endblock %}

{% block SectionTitle %}
<a class="text-secondary text-decoration-none" href="{% url 'band_portal:projects' %}">{% trans 'Projects| '%}</a>
<a class="text-secondary text-decoration-none" href="{% url 'band_portal:project' project.slug %}">{{ project.name }}| </a>
{% block SectionTitleAddition %}

{% endblock %}
{% endblock %}

{% block Content %}

{% endblock %}

tid_portal/band_portal/templates/band_portal/tabulatures.html
{% extends 'band_portal/base.html' %}
{% load i18n %}

{% block Title %}
{% trans 'Tabulatures' %}
{% endblock %}

{% block SectionTitle %}
{% trans 'Tabulatures' %}
{% endblock %}

{% block AdditionalButtons %}
<div class="btn-toolbar mb-2 mb-md-0">
    <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:tabulatures_download_actual' %}">{% trans 'Download actual' %}</a>
    <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'band_portal:tabulature_create' %}">{% trans 'New tabulature' %}</a>
</div>
{% endblock %}

{% block Content %}

{% for tabulature in tabulatures %}
    <a href="{% url 'band_portal:tabulature' tabulature.id %}" class="text-secondary">
            {{ tabulature.name}}
    </a>
<br />
{% endfor %}
{% endblock %}